# SPDX-License-Identifier: Apache-2.0
"""The paper's Fig. 4 as a repo test, with neutral names (PLAN-v0.14 §3 row P2).

Fig. 4 is a falsification graph: parameters feed derived values, derived values
feed evaluators, evaluators settle claims, and a change travels exactly the
edges it reaches. Here it is a generated project with no case-study content —
an enclosure, a port, a cable, a reach, a power budget and a firmware revision —
in which every evaluator is a project gate with both controls and the mutation
pass (P2.3), so every read set is traced, never declared:

    cavity_w ─┬─> enclosure ──> fig4.enclosure_fit ─> K1 enclosure fits
              ├─> port_pos ──┬> fig4.port_align ───> K2 port meets the connector
              │              └> cable_len ─> fig4.cable ─> K3 cable adequate
              └────────────────> fig4.reach (context cavity_w in [60, 75]) ─> K4 reach
    cell_mah ───> board ──────> fig4.power ────────> K6 power budget
    fw_rev ─────> firmware ───> fig4.firmware ─────> K7 firmware behaves
    (the whole design) ───────> a physical article ─> K5 printed parts assemble

**Base case.** After a check run at ``cavity_w`` 70, the cavity goes to 82 with
no check run: K1-K3 read Stale (their derived reads moved), K4 Assumed under its
owned fallback (82 lies outside its evaluator's context, and its owner recorded
the fallback in their own shell), K5 Pending build (never built), K6 and K7
Checked (nothing they read moved), and the rebuild prediction is empty.

**Controls**, one test each: a change it must not reach (the base case's K6,
K7); an unregistered read; the operating context removed; the owner removed
(critique 19 of the P2.5a design: recorded first, then removed); a change inside
the context; a fail outside the context; a physical pass on an article whose
read set moved. Two planted resolvers the base case must catch.

Run:  PYTHONPATH=src python3 -m unittest discover -s tests -p test_fig4.py -v
"""
from __future__ import annotations

import json
import os
import tempfile
import unittest
from typing import Any, Mapping
from unittest import mock

import _env
import _physical as P
import _projects
from nopekit import verdicts

MODEL = '''\
"""Fig. 4's design, generated by tests/test_fig4.py: three inputs, five derived values."""
from dataclasses import dataclass


@dataclass
class Config:
    cavity_w: float = {cavity_w}
    cell_mah: float = 2000.0
    fw_rev: float = 3.0


CONFIG = Config()


def build(config=None):
    c = config if config is not None else CONFIG
    port_pos = round(c.cavity_w / 2.0, 6)
    return {{"enclosure": round(c.cavity_w + 6.0, 6), "port_pos": port_pos,
             "cable_len": round(port_pos + 20.0, 6), "board": round(c.cell_mah * 0.01, 6),
             "firmware": round(c.fw_rev * 1.0, 6)}}
'''

#: ``{context}`` is the reach evaluator's declaration, or nothing (the context
#: removed); ``{cable_read}`` is how the cable evaluator reads its value — from
#: its parameter, or through an environment variable no tracer registers.
GATES = '''\
"""Fig. 4's evaluators, generated by tests/test_fig4.py."""
import os

from nopekit.gates import gate
from nopekit.models import NegativeControl, Verdict


def _bad(name):
    return NegativeControl(fixture=f"selftest/bad.py:{{name}}", note=name)


def _judge(gate_id, value, limit, units, comparator):
    ok = value <= limit if comparator == "<=" else value >= limit
    return Verdict(gate=gate_id, passed=ok, measured=round(value, 4), limit=limit,
                   units=units, comparator=comparator,
                   detail=f"{{value:.3f}} {{units}} (limit {{limit}} {{units}})")


@gate(id="fig4.enclosure_fit", claims=["K1"], settles="enclosure width",
      negative_control=_bad("wide"))
def enclosure_fit(ctx):
    return _judge("fig4.enclosure_fit", float(ctx.params["enclosure"]), 100.0, "mm", "<=")


@gate(id="fig4.port_align", claims=["K2"], settles="port offset",
      negative_control=_bad("offset"))
def port_align(ctx):
    return _judge("fig4.port_align", float(ctx.params["port_pos"]), 45.0, "mm", "<=")


@gate(id="fig4.cable", claims=["K3"], settles="cable length",
      negative_control=_bad("long"))
def cable(ctx):
    value = {cable_read}
    return _judge("fig4.cable", value, 70.0, "mm", "<=")


@gate(id="fig4.reach", claims=["K4"], settles="reach", {context}
      negative_control=_bad("deep"))
def reach(ctx):
    return _judge("fig4.reach", float(ctx.params["cavity_w"]), 90.0, "mm", "<=")


@gate(id="fig4.power", claims=["K6"], settles="board power",
      negative_control=_bad("hungry"))
def power(ctx):
    return _judge("fig4.power", float(ctx.params["board"]), 40.0, "W", "<=")


@gate(id="fig4.firmware", claims=["K7"], settles="firmware revision",
      negative_control=_bad("old"))
def firmware(ctx):
    return _judge("fig4.firmware", float(ctx.params["firmware"]), 2.0, "rev", ">=")
'''

CONTEXT = 'operating_context={"cavity_w": (60.0, 75.0)},'
CABLE_TRACED = 'float(ctx.params["cable_len"])'
CABLE_UNREGISTERED = ('float(os.environ.get("FIG4_CAVITY", "70")) / 2.0 + 20.0 '
                      '+ 0.0 * float(ctx.params["cable_len"])')

FIXTURES = '''\
"""Fig. 4's known-bad controls: each the known-good design with one change."""
import copy
import dataclasses
import os

from nopekit.modelio import load_path

kg = load_path(os.path.join(os.path.dirname(os.path.abspath(__file__)), "known_good.py"))


def _with(ctx, **over):
    params = copy.deepcopy(kg.PARAMS)
    params.update(over)
    return dataclasses.replace(kg.context(ctx), params=params)


def wide(ctx):
    return _with(ctx, enclosure=140.0)


def offset(ctx):
    return _with(ctx, port_pos=60.0)


def long(ctx):
    return _with(ctx, cable_len=95.0)


def deep(ctx):
    return _with(ctx, cavity_w=120.0)


def hungry(ctx):
    return _with(ctx, board=55.0)


def old(ctx):
    return _with(ctx, firmware=1.0)
'''


def _claim(statement: str, quantity: str, comparator: str, limit: float,
           units: str) -> dict:
    return {"statement": statement, "kind": "measurable",
            "acceptance": {"quantity": quantity, "comparator": comparator, "limit": limit,
                           "units": units}}


CLAIMS: dict[str, dict] = {
    "K1": _claim("The enclosure fits the bay", "enclosure width", "<=", 100.0, "mm"),
    "K2": _claim("The port meets the connector", "port offset", "<=", 45.0, "mm"),
    "K3": _claim("The cable is long enough and no longer", "cable length", "<=", 70.0, "mm"),
    "K4": dict(_claim("The reach is comfortable", "reach", "<=", 90.0, "mm"),
               owner=P.NAME, fallback="reach scales linearly with the cavity past 75 mm"),
    "K5": {"statement": "The printed parts assemble", "kind": "physical",
           "note": "assemble the printed parts by hand; no forcing, no gaps over 0.5 mm"},
    "K6": _claim("The power budget holds", "board power", "<=", 40.0, "W"),
    "K7": _claim("The firmware behaves", "firmware revision", ">=", 2.0, "rev"),
}


def known_good(cavity_w: float = 70.0) -> dict[str, Any]:
    port = round(cavity_w / 2.0, 6)
    config = {"cavity_w": cavity_w, "cell_mah": 2000.0, "fw_rev": 3.0}
    derived = {"enclosure": round(cavity_w + 6.0, 6), "port_pos": port,
               "cable_len": round(port + 20.0, 6), "board": 20.0, "firmware": 3.0}
    from nopekit import modelio
    return modelio.flat_params({"config": config, "derived": derived})[0]


#: P2.5b: two neutral generators — the enclosure's print reads the enclosure and
#: the port, the board's order reads the board — so an export's article is what
#: its generator read, and a change reaches exactly the articles it reaches.
ENCLOSURE_GENERATOR = '''\
"""Fig. 4's enclosure print, generated by tests/test_fig4.py."""
import os


def shell(ctx):
    with open(os.path.join(ctx.out_dir, "enclosure.txt"), "w", encoding="utf-8") as fh:
        fh.write(f"enclosure {ctx.params['enclosure']} mm, port at {ctx.params['port_pos']} mm\\n")
'''

BOARD_GENERATOR = '''\
"""Fig. 4's board order, generated by tests/test_fig4.py."""
import os


def layout(ctx):
    power = {board_read}
    with open(os.path.join(ctx.out_dir, "board.txt"), "w", encoding="utf-8") as fh:
        fh.write(f"board {{power}} W\\n")
'''

#: The board generator's read: its parameter, or the cell capacity through an
#: environment variable no tracer registers (V-8's control: never under-predict).
BOARD_TRACED = 'float(ctx.params["board"])'
BOARD_UNREGISTERED = ('float(os.environ.get("FIG4_CELL", "2000")) * 0.01 '
                      '+ 0.0 * float(ctx.params["board"])')

GENERATORS = {"generators/enclosure.py": ENCLOSURE_GENERATOR,
              "generators/board.py": BOARD_GENERATOR.format(board_read=BOARD_TRACED)}

MILESTONES = {
    "enclosure": {"description": "Print the enclosure", "requires": ["K1", "K2", "K3"],
                  "generator": "generators/enclosure.py:shell"},
    "board": {"description": "Order the board", "requires": ["K6", "K7"],
              "generator": "generators/board.py:layout"},
}

#: A second physical claim, on the board's article (V-8). Kept out of CLAIMS
#: (critique 22 of the P2.5b design): P2.5a's rows iterate CLAIMS, and K8 would
#: read Pending build there.
K8 = {"statement": "The board powers up", "kind": "physical",
      "note": "power the board from the bench supply; it boots to its prompt",
      "expected_latency": {"value": 1, "units": "day"}}


def fig4(dest: str, *, context: str = CONTEXT, cable: str = CABLE_TRACED,
         extra_claims: Mapping[str, dict] | None = None,
         generators: Mapping[str, str] | None = None,
         milestones: Mapping[str, dict] | None = None) -> str:
    files = {"model/m.py": MODEL.format(cavity_w="70.0"),
             "gates/g.py": GATES.format(context=context, cable_read=cable),
             "selftest/bad.py": FIXTURES, **dict(generators or {})}
    good_claims = [{"id": cid, **record} for cid, record in CLAIMS.items()
                   if record["kind"] == "measurable"]
    root = _projects.plant_project(dest, files, claims={**CLAIMS, **dict(extra_claims or {})},
                                   known_good_params=known_good(),
                                   known_good_claims=good_claims)
    for name, record in (milestones or {}).items():
        P.write_json(os.path.join(root, "milestones", f"{name}.json"), record)
    return root


def set_config(root: str, name: str, value: float) -> None:
    """Edit one of the model's inputs in place, as a person would type it."""
    path = os.path.join(root, "model", "m.py")
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines(keepends=True)
    hits = [i for i, ln in enumerate(lines) if ln.startswith(f"    {name}: float = ")]
    assert len(hits) == 1, hits
    lines[hits[0]] = f"    {name}: float = {float(value)!r}\n"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(lines))


def set_cavity(root: str, value: float) -> None:
    set_config(root, "cavity_w", value)


def export(root: str, name: str, *args: str, code: int | None = None) -> dict:
    """``nopekit export <name> <args> --json``'s document."""
    proc = P.run(root, "export", name, *args, "--json", code=code)
    try:
        return json.loads(proc.stdout)
    except ValueError:
        raise AssertionError(f"`export {name}` printed no JSON (exit {proc.returncode}):\n"
                             f"{proc.stdout[-2000:]}\n{proc.stderr[-2000:]}") from None


def evidence(root: str, name: str = "k5.jpg") -> str:
    """A photo under the project, for a pass that needs one; its relative path."""
    os.makedirs(os.path.join(root, "photos"), exist_ok=True)
    with open(os.path.join(root, "photos", name), "wb") as fh:
        fh.write(b"\xff\xd8 " + name.encode() + b" \xff\xd9")
    return f"photos/{name}"


def statuses(root: str) -> dict[str, tuple[str, str]]:
    doc = json.loads(P.run(root, "status", "--json", code=0).stdout)
    return {cid: (doc["claims"][cid], doc["statuses"][cid]["cause"]) for cid in CLAIMS}


#: The base case, as the falsification graph says it must read.
BASE = {"K1": ("stale", "invalidated"), "K2": ("stale", "invalidated"),
        "K3": ("stale", "invalidated"), "K4": ("asserted", "fallback"),
        "K5": ("unverified", "no-article"), "K6": ("pass", "checked"),
        "K7": ("pass", "checked")}


def base_problems(found: Mapping[str, tuple[str, str]]) -> list[str]:
    return [f"{cid}: {found.get(cid)}, not {want}" for cid, want in BASE.items()
            if tuple(found.get(cid) or ()) != want]


def _record_owner(root: str) -> None:
    P.tty(root, "claim", "physical", "K4", "assume", answer="K4", code=0)


class FalsificationGraphOfFigure4(_env.EnvCase):
    """(V-19; PLAN-v0.14 §3 row P2's done criterion)"""

    @classmethod
    def setUpClass(cls):
        cls.tmpdir = tempfile.mkdtemp(prefix="nopekit-fig4-")
        root = fig4(os.path.join(cls.tmpdir, "base"))
        P.run(root, "check")
        cls.at70 = statuses(root)
        _record_owner(root)
        set_cavity(root, 82.0)
        cls.root = root
        cls.base = statuses(root)
        cls.doc = json.loads(P.run(root, "status", "--json", code=0).stdout)

    @classmethod
    def tearDownClass(cls):
        _env._rmtree(cls.tmpdir)

    def test_every_evaluator_qualified_and_checked_at_70(self):
        self.assertEqual({cid: s for cid, s in self.at70.items() if cid != "K5"},
                         {cid: ("pass", "checked") for cid in CLAIMS if cid != "K5"})

    def test_the_base_case(self):
        self.assertEqual(base_problems(self.base), [])
        self.assertEqual(self.doc.get("rebuild"), [])

    def test_a_resolver_staling_on_the_whole_model_is_caught(self):
        """Planted: every gate stale once anything in the model moved."""
        real = verdicts._judge

        def whole_model(spec, code, entries, now, order):
            state = real(spec, code, entries, now, order)
            if isinstance(state, verdicts.Fresh):
                return verdicts.Stale(entries[0], ("model changed",)) if entries else state
            return state

        with mock.patch.object(verdicts, "_judge", whole_model):
            found = {cid: (c.status.value, c.cause.value)
                     for cid, c in _composed_in_process(self.root).items()}
        self.assertTrue(base_problems(found), "a whole-model resolver was not caught")

    def test_an_unregistered_read_never_reads_checked(self):
        root = fig4(os.path.join(self.tmp(), "env"), cable=CABLE_UNREGISTERED)
        P.run(root, "check")
        self.assertNotEqual(statuses(root)["K3"], ("pass", "checked"))

    def test_the_operating_context_removed(self):
        root = fig4(os.path.join(self.tmp(), "noctx"))
        P.run(root, "check")
        _record_owner(root)
        with open(os.path.join(root, "gates", "g.py"), "w", encoding="utf-8") as fh:
            fh.write(GATES.format(context="", cable_read=CABLE_TRACED))
        set_cavity(root, 82.0)
        self.assertEqual(statuses(root)["K4"][0], "stale")
        P.run(root, "check")
        self.assertEqual(statuses(root)["K4"], ("pass", "checked"))

    def test_the_owner_removed(self):
        """Recorded first, then removed from the claim file: the attribution no
        longer counts, and the pass outside the context reads Gap."""
        root = fig4(os.path.join(self.tmp(), "owner"))
        P.run(root, "check")
        _record_owner(root)
        set_cavity(root, 82.0)
        self.assertEqual(statuses(root)["K4"], ("asserted", "fallback"))
        P.edit_claim(root, "K4", owner=None)
        self.assertEqual(statuses(root)["K4"], ("unclaimed", "outside-context"))

    def test_a_change_inside_the_context(self):
        root = fig4(os.path.join(self.tmp(), "inside"))
        P.run(root, "check")
        _record_owner(root)
        set_cavity(root, 72.0)
        self.assertEqual(statuses(root)["K4"], ("stale", "invalidated"))

    def test_a_fail_outside_the_context_stays_failing(self):
        root = fig4(os.path.join(self.tmp(), "fail"))
        P.run(root, "check")
        _record_owner(root)
        set_cavity(root, 95.0)
        P.run(root, "check")
        self.assertEqual(statuses(root)["K4"][0], "fail")

    def test_a_physical_pass_on_a_moved_article(self):
        root = fig4(os.path.join(self.tmp(), "article"))
        P.run(root, "check")
        os.makedirs(os.path.join(root, "photos"))
        with open(os.path.join(root, "photos", "k5.jpg"), "wb") as fh:
            fh.write(b"\xff\xd8 the parts, assembled \xff\xd9")
        P.tty(root, "claim", "physical", "K5", "pass", "--detail", "assembled by hand",
              "--evidence", "photos/k5.jpg", answer="K5", code=0)
        article = P.results(root, "K5")["results"][-1]["article"]["hash"]
        self.assertEqual(statuses(root)["K5"], ("verified", "on-article"))
        set_cavity(root, 82.0)
        self.assertEqual(statuses(root)["K5"], ("stale", "article-moved"))
        doc = json.loads(P.run(root, "status", "--json", code=0).stdout)
        self.assertEqual([(r["article"], r["claims"]) for r in doc["rebuild"]],
                         [(article, ["K5"])])


def _composed_in_process(root: str) -> dict:
    from nopekit import claims
    view, resolution = P.resolved(root)
    return claims.compositions(view, stale_gates=resolution.stale_gates)


# --------------------------------------------------------------------------- #
# V-8 (P2.5b) — two exported articles, each moved by exactly what it was built from
# --------------------------------------------------------------------------- #
def _rebuild(root: str) -> list[tuple[str, list[str]]]:
    doc = json.loads(P.run(root, "status", "--json", code=0).stdout)
    return [(r["article"], list(r["claims"])) for r in doc.get("rebuild") or ()]


def _record_pass(root: str, cid: str, article: str) -> None:
    photo = evidence(root, f"{cid.lower()}.jpg")
    P.tty(root, "claim", "physical", cid, "pass", "--detail", "as the note says",
          "--evidence", photo, "--article", article, answer=cid, code=0)


def two_articles(dest: str, *, board: str = BOARD_TRACED) -> tuple[str, str, str]:
    """Fig. 4 with both milestones exported at ``cavity_w`` 70 and a pass on each
    article — K5 on the enclosure's, K8 on the board's: ``(root, E, B)``."""
    generators = dict(GENERATORS)
    generators["generators/board.py"] = BOARD_GENERATOR.format(board_read=board)
    root = fig4(dest, extra_claims={"K8": K8}, generators=generators, milestones=MILESTONES)
    _projects._commit_all(root, "fig4")
    P.run(root, "check")
    enclosure = export(root, "enclosure", code=0)["article"]["hash"]
    board_ = export(root, "board", code=0)["article"]["hash"]
    _record_pass(root, "K5", enclosure)
    _record_pass(root, "K8", board_)
    return root, enclosure, board_


class TwoArticlesExactly(_env.EnvCase):
    """(V-8, invariants 7 and 11; P2.5a-D16's hand-off) An exported article is
    what its generator read. A change moves exactly the exported articles whose
    read set it reaches, and the rebuild prediction names exactly those: the
    cavity moves the enclosure's and not the board's, the cell the board's and
    not the enclosure's, and the firmware revision — which neither generator
    read, and neither package carries — neither."""

    @classmethod
    def setUpClass(cls):
        import tempfile as _tempfile
        cls.tmpdir = _tempfile.mkdtemp(prefix="nopekit-fig4-two-")
        cls.root, cls.E, cls.B = two_articles(os.path.join(cls.tmpdir, "two"))

    @classmethod
    def tearDownClass(cls):
        _env._rmtree(cls.tmpdir)

    def _at(self, name: str, value: float, *, reset: float) -> tuple[dict, list]:
        set_config(self.root, name, value)
        try:
            doc = json.loads(P.run(self.root, "status", "--json", code=0).stdout)
            found = {cid: (doc["claims"][cid], doc["statuses"][cid]["cause"])
                     for cid in ("K5", "K8")}
            return found, [(r["article"], list(r["claims"])) for r in doc.get("rebuild") or ()]
        finally:
            set_config(self.root, name, reset)

    def test_both_count_at_seventy(self):
        found, rebuild = self._at("cavity_w", 70.0, reset=70.0)
        self.assertEqual(found, {"K5": ("verified", "on-article"),
                                 "K8": ("verified", "on-article")})
        self.assertEqual(rebuild, [])

    def test_the_cavity_moves_the_enclosure_alone(self):
        found, rebuild = self._at("cavity_w", 82.0, reset=70.0)
        self.assertEqual(found["K5"], ("stale", "article-moved"))
        self.assertEqual(found["K8"], ("verified", "on-article"))
        self.assertEqual(rebuild, [(self.E, ["K5"])])

    def test_the_cell_moves_the_board_alone(self):
        found, rebuild = self._at("cell_mah", 2500.0, reset=2000.0)
        self.assertEqual(found["K8"], ("stale", "article-moved"))
        self.assertEqual(found["K5"], ("verified", "on-article"))
        self.assertEqual(rebuild, [(self.B, ["K8"])])

    def test_a_change_no_generator_read_moves_neither(self):
        found, rebuild = self._at("fw_rev", 4.0, reset=3.0)
        self.assertEqual(found, {"K5": ("verified", "on-article"),
                                 "K8": ("verified", "on-article")})
        self.assertEqual(rebuild, [])

    def test_each_package_carries_only_what_its_article_records(self):
        """Critique 1 of the P2.5b design: a value the package hands the builder
        but the article never recorded would be a change that moves nothing. The
        board's `model.json` holds the board and nothing else — no firmware."""
        with open(os.path.join(self.root, "out", "board", "model.json"),
                  encoding="utf-8") as fh:
            carried = json.load(fh)
        self.assertEqual(package_problems(carried, self.root, "board"), [])
        self.assertTrue(package_problems({**carried, "fw_rev": 3.0}, self.root, "board"),
                        "a package carrying a value its article does not record was not "
                        "caught")

    def test_an_unregistered_read_never_under_predicts(self):
        """The control: a board generator reading the cell through an environment
        variable is untraced — its article is the whole design — so the cavity
        change names it too."""
        root, enclosure, board_ = two_articles(os.path.join(self.tmp(), "env"),
                                               board=BOARD_UNREGISTERED)
        exported = P.exports(root, "board")["exports"][-1]["article"]
        self.assertIs(exported.get("traced"), False)
        set_cavity(root, 82.0)
        self.assertEqual(sorted(_rebuild(root)), sorted([(enclosure, ["K5"]),
                                                         (board_, ["K8"])]))

    def test_the_planted_predictions_are_caught(self):
        """Planted: a prediction naming every exported article, and an exported
        article compared against the whole design."""
        from nopekit import claims as claims_mod
        real = claims_mod.rebuild

        def everything(ledger):
            found = real(ledger)
            named = {r.article for r in found}
            for claim in ledger.claims:
                for entry in getattr(claim, "results", ()) or ():
                    article = getattr(entry, "article", None) or {}
                    if article.get("source") == "export" and article["hash"] not in named:
                        found.append(claims_mod.Rebuild(article["hash"], (claim.id,), ()))
                        named.add(article["hash"])
            return found

        set_config(self.root, "cavity_w", 82.0)
        try:
            with mock.patch.object(claims_mod, "rebuild", everything):
                view, _resolution = P.resolved(self.root)
                planted = sorted(r.article for r in claims_mod.rebuild(view))
        finally:
            set_config(self.root, "cavity_w", 70.0)
        self.assertNotEqual(planted, [self.E], "a prediction naming everything was not caught")

        before = dict(_flat(self.root))
        real_moves = verdicts._article_moves

        def whole_design(article, here):
            if article.get("traced") and dict(here.flat or {}) != before:
                return "moved", ("the design changed",)
            return real_moves(article, here)

        set_config(self.root, "fw_rev", 4.0)
        try:
            with mock.patch.object(verdicts, "_article_moves", whole_design):
                view, _resolution = P.resolved(self.root)
                planted = claims_mod.rebuild(view)
        finally:
            set_config(self.root, "fw_rev", 3.0)
        self.assertTrue(planted, "a whole-design comparison at fw_rev was not caught")


def _flat(root: str) -> dict:
    from nopekit import cli, modelio, store
    ledger = store.load(root)
    _model, projection, _error = cli._projection_safe(root, ledger)
    return modelio.flat_params(projection)[0]


def package_problems(carried: Mapping[str, Any], root: str, name: str) -> list[str]:
    """Every value a package's `model.json` carries that its export's article
    does not record (``built_from``'s params, by dotted path)."""
    article = P.exports(root, name)["exports"][-1]["article"]
    rows = {".".join(str(p) for p in row[0]) for row in article["built_from"]["params"]}
    return [key for key in carried if key not in rows]


class ExportAtTheBoundarySeesPastTheCache(_env.EnvCase):
    """(V-8's export rows; critique 8 of the P2.5b design) The base case — the
    cavity at 82 and no check run — reads K1-K3 Stale from the cache, and the
    boundary re-runs them: at 82 they pass, so `export enclosure --dry-run`
    reads them Checked and would write. The boundary saw past the cache; it
    never judges on the cache's Stale view (R-9)."""

    def test_the_base_case(self):
        root = fig4(os.path.join(self.tmp(), "base"), generators=GENERATORS,
                    milestones=MILESTONES)
        _projects._commit_all(root, "fig4")
        P.run(root, "check")
        set_cavity(root, 82.0)
        self.assertEqual({cid: statuses(root)[cid][0] for cid in ("K1", "K2", "K3")},
                         {"K1": "stale", "K2": "stale", "K3": "stale"})
        doc = export(root, "enclosure", "--dry-run", code=0)
        self.assertTrue(doc["ready"])
        self.assertEqual(sorted(r["gate"] for r in doc["reran"]),
                         ["fig4.cable", "fig4.enclosure_fit", "fig4.port_align"])
        board = export(root, "board", "--dry-run", code=0)
        self.assertEqual(sorted(r["gate"] for r in board["reran"]),
                         ["fig4.firmware", "fig4.power"])
        self.assertEqual({cid: statuses(root)[cid][0] for cid in ("K1", "K2", "K3")},
                         {"K1": "stale", "K2": "stale", "K3": "stale"},
                         "--dry-run filed its re-run")


if __name__ == "__main__":
    unittest.main(verbosity=2)
