# SPDX-License-Identifier: Apache-2.0
"""The paper's Fig. 4 as a repo test, with neutral names (PLAN-v0.14 §3 row P2).

Fig. 4 is a falsification graph: parameters feed derived values, derived values
feed evaluators, evaluators settle claims, and a change travels exactly the
edges it reaches. Here it is a generated project with no case-study content —
an enclosure, a port, a cable, a reach, a power budget and a firmware revision —
in which every evaluator is a project gate with both controls and the mutation
pass (P2.3), so every read set is traced, never declared:

    cavity_w ─┬─> enclosure ──> fig4.enclosure_fit ─> K1 enclosure fits
              ├─> port_pos ──┬> fig4.port_align ───> K2 port meets the connector
              │              └> cable_len ─> fig4.cable ─> K3 cable adequate
              └────────────────> fig4.reach (context cavity_w in [60, 75]) ─> K4 reach
    cell_mah ───> board ──────> fig4.power ────────> K6 power budget
    fw_rev ─────> firmware ───> fig4.firmware ─────> K7 firmware behaves
    (the whole design) ───────> a physical article ─> K5 printed parts assemble

**Base case.** After a check run at ``cavity_w`` 70, the cavity goes to 82 with
no check run: K1-K3 read Stale (their derived reads moved), K4 Assumed under its
owned fallback (82 lies outside its evaluator's context, and its owner recorded
the fallback in their own shell), K5 Pending build (never built), K6 and K7
Checked (nothing they read moved), and the rebuild prediction is empty.

**Controls**, one test each: a change it must not reach (the base case's K6,
K7); an unregistered read; the operating context removed; the owner removed
(critique 19 of the P2.5a design: recorded first, then removed); a change inside
the context; a fail outside the context; a physical pass on an article whose
read set moved. Two planted resolvers the base case must catch.

Run:  PYTHONPATH=src python3 -m unittest discover -s tests -p test_fig4.py -v
"""
from __future__ import annotations

import json
import os
import tempfile
import unittest
from typing import Any, Mapping
from unittest import mock

import _env
import _physical as P
import _projects
from atompipe import verdicts

MODEL = '''\
"""Fig. 4's design, generated by tests/test_fig4.py: three inputs, five derived values."""
from dataclasses import dataclass


@dataclass
class Config:
    cavity_w: float = {cavity_w}
    cell_mah: float = 2000.0
    fw_rev: float = 3.0


CONFIG = Config()


def build(config=None):
    c = config if config is not None else CONFIG
    port_pos = round(c.cavity_w / 2.0, 6)
    return {{"enclosure": round(c.cavity_w + 6.0, 6), "port_pos": port_pos,
             "cable_len": round(port_pos + 20.0, 6), "board": round(c.cell_mah * 0.01, 6),
             "firmware": round(c.fw_rev * 1.0, 6)}}
'''

#: ``{context}`` is the reach evaluator's declaration, or nothing (the context
#: removed); ``{cable_read}`` is how the cable evaluator reads its value — from
#: its parameter, or through an environment variable no tracer registers.
GATES = '''\
"""Fig. 4's evaluators, generated by tests/test_fig4.py."""
import os

from atompipe.gates import gate
from atompipe.models import NegativeControl, Verdict


def _bad(name):
    return NegativeControl(fixture=f"selftest/bad.py:{{name}}", note=name)


def _judge(gate_id, value, limit, units, comparator):
    ok = value <= limit if comparator == "<=" else value >= limit
    return Verdict(gate=gate_id, passed=ok, measured=round(value, 4), limit=limit,
                   units=units, comparator=comparator,
                   detail=f"{{value:.3f}} {{units}} (limit {{limit}} {{units}})")


@gate(id="fig4.enclosure_fit", claims=["K1"], settles="enclosure width",
      negative_control=_bad("wide"))
def enclosure_fit(ctx):
    return _judge("fig4.enclosure_fit", float(ctx.params["enclosure"]), 100.0, "mm", "<=")


@gate(id="fig4.port_align", claims=["K2"], settles="port offset",
      negative_control=_bad("offset"))
def port_align(ctx):
    return _judge("fig4.port_align", float(ctx.params["port_pos"]), 45.0, "mm", "<=")


@gate(id="fig4.cable", claims=["K3"], settles="cable length",
      negative_control=_bad("long"))
def cable(ctx):
    value = {cable_read}
    return _judge("fig4.cable", value, 70.0, "mm", "<=")


@gate(id="fig4.reach", claims=["K4"], settles="reach", {context}
      negative_control=_bad("deep"))
def reach(ctx):
    return _judge("fig4.reach", float(ctx.params["cavity_w"]), 90.0, "mm", "<=")


@gate(id="fig4.power", claims=["K6"], settles="board power",
      negative_control=_bad("hungry"))
def power(ctx):
    return _judge("fig4.power", float(ctx.params["board"]), 40.0, "W", "<=")


@gate(id="fig4.firmware", claims=["K7"], settles="firmware revision",
      negative_control=_bad("old"))
def firmware(ctx):
    return _judge("fig4.firmware", float(ctx.params["firmware"]), 2.0, "rev", ">=")
'''

CONTEXT = 'operating_context={"cavity_w": (60.0, 75.0)},'
CABLE_TRACED = 'float(ctx.params["cable_len"])'
CABLE_UNREGISTERED = ('float(os.environ.get("FIG4_CAVITY", "70")) / 2.0 + 20.0 '
                      '+ 0.0 * float(ctx.params["cable_len"])')

FIXTURES = '''\
"""Fig. 4's known-bad controls: each the known-good design with one change."""
import copy
import dataclasses
import os

from atompipe.modelio import load_path

kg = load_path(os.path.join(os.path.dirname(os.path.abspath(__file__)), "known_good.py"))


def _with(ctx, **over):
    params = copy.deepcopy(kg.PARAMS)
    params.update(over)
    return dataclasses.replace(kg.context(ctx), params=params)


def wide(ctx):
    return _with(ctx, enclosure=140.0)


def offset(ctx):
    return _with(ctx, port_pos=60.0)


def long(ctx):
    return _with(ctx, cable_len=95.0)


def deep(ctx):
    return _with(ctx, cavity_w=120.0)


def hungry(ctx):
    return _with(ctx, board=55.0)


def old(ctx):
    return _with(ctx, firmware=1.0)
'''


def _claim(statement: str, quantity: str, comparator: str, limit: float,
           units: str) -> dict:
    return {"statement": statement, "kind": "measurable",
            "acceptance": {"quantity": quantity, "comparator": comparator, "limit": limit,
                           "units": units}}


CLAIMS: dict[str, dict] = {
    "K1": _claim("The enclosure fits the bay", "enclosure width", "<=", 100.0, "mm"),
    "K2": _claim("The port meets the connector", "port offset", "<=", 45.0, "mm"),
    "K3": _claim("The cable is long enough and no longer", "cable length", "<=", 70.0, "mm"),
    "K4": dict(_claim("The reach is comfortable", "reach", "<=", 90.0, "mm"),
               owner=P.NAME, fallback="reach scales linearly with the cavity past 75 mm"),
    "K5": {"statement": "The printed parts assemble", "kind": "physical",
           "note": "assemble the printed parts by hand; no forcing, no gaps over 0.5 mm"},
    "K6": _claim("The power budget holds", "board power", "<=", 40.0, "W"),
    "K7": _claim("The firmware behaves", "firmware revision", ">=", 2.0, "rev"),
}


def known_good(cavity_w: float = 70.0) -> dict[str, Any]:
    port = round(cavity_w / 2.0, 6)
    config = {"cavity_w": cavity_w, "cell_mah": 2000.0, "fw_rev": 3.0}
    derived = {"enclosure": round(cavity_w + 6.0, 6), "port_pos": port,
               "cable_len": round(port + 20.0, 6), "board": 20.0, "firmware": 3.0}
    from atompipe import modelio
    return modelio.flat_params({"config": config, "derived": derived})[0]


def fig4(dest: str, *, context: str = CONTEXT, cable: str = CABLE_TRACED) -> str:
    files = {"model/m.py": MODEL.format(cavity_w="70.0"),
             "gates/g.py": GATES.format(context=context, cable_read=cable),
             "selftest/bad.py": FIXTURES}
    good_claims = [{"id": cid, **record} for cid, record in CLAIMS.items()
                   if record["kind"] == "measurable"]
    return _projects.plant_project(dest, files, claims=CLAIMS,
                                   known_good_params=known_good(),
                                   known_good_claims=good_claims)


def set_cavity(root: str, value: float) -> None:
    path = os.path.join(root, "model", "m.py")
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines(keepends=True)
    hits = [i for i, ln in enumerate(lines) if ln.startswith("    cavity_w: float = ")]
    assert len(hits) == 1, hits
    lines[hits[0]] = f"    cavity_w: float = {float(value)!r}\n"
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(lines))


def statuses(root: str) -> dict[str, tuple[str, str]]:
    doc = json.loads(P.run(root, "status", "--json", code=0).stdout)
    return {cid: (doc["claims"][cid], doc["statuses"][cid]["cause"]) for cid in CLAIMS}


#: The base case, as the falsification graph says it must read.
BASE = {"K1": ("stale", "invalidated"), "K2": ("stale", "invalidated"),
        "K3": ("stale", "invalidated"), "K4": ("asserted", "fallback"),
        "K5": ("unverified", "no-article"), "K6": ("pass", "checked"),
        "K7": ("pass", "checked")}


def base_problems(found: Mapping[str, tuple[str, str]]) -> list[str]:
    return [f"{cid}: {found.get(cid)}, not {want}" for cid, want in BASE.items()
            if tuple(found.get(cid) or ()) != want]


def _record_owner(root: str) -> None:
    P.tty(root, "claim", "physical", "K4", "assume", answer="K4", code=0)


class FalsificationGraphOfFigure4(_env.EnvCase):
    """(V-19; PLAN-v0.14 §3 row P2's done criterion)"""

    @classmethod
    def setUpClass(cls):
        cls.tmpdir = tempfile.mkdtemp(prefix="atompipe-fig4-")
        root = fig4(os.path.join(cls.tmpdir, "base"))
        P.run(root, "check")
        cls.at70 = statuses(root)
        _record_owner(root)
        set_cavity(root, 82.0)
        cls.root = root
        cls.base = statuses(root)
        cls.doc = json.loads(P.run(root, "status", "--json", code=0).stdout)

    @classmethod
    def tearDownClass(cls):
        _env._rmtree(cls.tmpdir)

    def test_every_evaluator_qualified_and_checked_at_70(self):
        self.assertEqual({cid: s for cid, s in self.at70.items() if cid != "K5"},
                         {cid: ("pass", "checked") for cid in CLAIMS if cid != "K5"})

    def test_the_base_case(self):
        self.assertEqual(base_problems(self.base), [])
        self.assertEqual(self.doc.get("rebuild"), [])

    def test_a_resolver_staling_on_the_whole_model_is_caught(self):
        """Planted: every gate stale once anything in the model moved."""
        real = verdicts._judge

        def whole_model(spec, code, entries, now, order):
            state = real(spec, code, entries, now, order)
            if isinstance(state, verdicts.Fresh):
                return verdicts.Stale(entries[0], ("model changed",)) if entries else state
            return state

        with mock.patch.object(verdicts, "_judge", whole_model):
            found = {cid: (c.status.value, c.cause.value)
                     for cid, c in _composed_in_process(self.root).items()}
        self.assertTrue(base_problems(found), "a whole-model resolver was not caught")

    def test_an_unregistered_read_never_reads_checked(self):
        root = fig4(os.path.join(self.tmp(), "env"), cable=CABLE_UNREGISTERED)
        P.run(root, "check")
        self.assertNotEqual(statuses(root)["K3"], ("pass", "checked"))

    def test_the_operating_context_removed(self):
        root = fig4(os.path.join(self.tmp(), "noctx"))
        P.run(root, "check")
        _record_owner(root)
        with open(os.path.join(root, "gates", "g.py"), "w", encoding="utf-8") as fh:
            fh.write(GATES.format(context="", cable_read=CABLE_TRACED))
        set_cavity(root, 82.0)
        self.assertEqual(statuses(root)["K4"][0], "stale")
        P.run(root, "check")
        self.assertEqual(statuses(root)["K4"], ("pass", "checked"))

    def test_the_owner_removed(self):
        """Recorded first, then removed from the claim file: the attribution no
        longer counts, and the pass outside the context reads Gap."""
        root = fig4(os.path.join(self.tmp(), "owner"))
        P.run(root, "check")
        _record_owner(root)
        set_cavity(root, 82.0)
        self.assertEqual(statuses(root)["K4"], ("asserted", "fallback"))
        P.edit_claim(root, "K4", owner=None)
        self.assertEqual(statuses(root)["K4"], ("unclaimed", "outside-context"))

    def test_a_change_inside_the_context(self):
        root = fig4(os.path.join(self.tmp(), "inside"))
        P.run(root, "check")
        _record_owner(root)
        set_cavity(root, 72.0)
        self.assertEqual(statuses(root)["K4"], ("stale", "invalidated"))

    def test_a_fail_outside_the_context_stays_failing(self):
        root = fig4(os.path.join(self.tmp(), "fail"))
        P.run(root, "check")
        _record_owner(root)
        set_cavity(root, 95.0)
        P.run(root, "check")
        self.assertEqual(statuses(root)["K4"][0], "fail")

    def test_a_physical_pass_on_a_moved_article(self):
        root = fig4(os.path.join(self.tmp(), "article"))
        P.run(root, "check")
        os.makedirs(os.path.join(root, "photos"))
        with open(os.path.join(root, "photos", "k5.jpg"), "wb") as fh:
            fh.write(b"\xff\xd8 the parts, assembled \xff\xd9")
        P.tty(root, "claim", "physical", "K5", "pass", "--detail", "assembled by hand",
              "--evidence", "photos/k5.jpg", answer="K5", code=0)
        article = P.results(root, "K5")["results"][-1]["article"]["hash"]
        self.assertEqual(statuses(root)["K5"], ("verified", "on-article"))
        set_cavity(root, 82.0)
        self.assertEqual(statuses(root)["K5"], ("stale", "article-moved"))
        doc = json.loads(P.run(root, "status", "--json", code=0).stdout)
        self.assertEqual([(r["article"], r["claims"]) for r in doc["rebuild"]],
                         [(article, ["K5"])])


def _composed_in_process(root: str) -> dict:
    from atompipe import claims
    view, resolution = P.resolved(root)
    return claims.compositions(view, stale_gates=resolution.stale_gates)


if __name__ == "__main__":
    unittest.main(verbosity=2)
